### ISSUE TITLE
[Request]Possible to come out an API doc?

### ISSUE THREAD

**Issue by weilies** [GymbylCoding/Dusk-Engine#33]
Hi Sir,

Thanks for making such a great tool.
I am planning to create puzzle game, which each layer represent a level in my game (for example candy crush's level).

So with your Dusk engine, possible for me only load up specific layer? (e.g. LEVEL 100 will only show layer 100)

And hopefully there is a API doc so i dont need to study your giant code.

Thanks & have a nice day.

**Comment by GymbylCoding** [comment]
Dusk now supports changing a single tile with either tile animations or the `!isSprite!` property for a tile. Closing this issue.
