### ISSUE TITLE
dynamic content scaling behaviors ignored

### ISSUE THREAD

**Issue by wiiiim** [GymbylCoding/Dusk-Engine#35]
Specifying scaling options in a corona project config file ('letterBox', 'zoomEven' or 'zoomStretch' are the current options) does not affect how all content generated from Tiled is scaled.

Example: i'm using 'letterBox' in the config file, but all my tiles and shapes coming from Tiled are being stretched in a 'zoomStretch' fashion to fit the screen. The only things that actually do scale according to the config are image layers.

**Comment by GymbylCoding** [comment]
This has been fixed; sorry for losing track of this issue.
