### ISSUE TITLE
Feature Request: allow custom viewport size

### ISSUE THREAD

**Issue by bitinn** [GymbylCoding/Dusk-Engine#43]
By `viewport` I mean the visible size of the map, by default it's the same as the device viewport, but is it possible to set it to a custom size, relative to device viewport size? say a square with all sides equal to screen width (for example, it would be 375 x 375 on iphone 6).

Of course, one could just ignore it and overlay UI on top of the map, but it seems like a waste to me to render unnecessarily. And what if I want 2 map on screen at the same time (say in a local multiplayer game)? 

Apologize in advance if I am overlooking something obvious (like a creative use of `setCameraBounds`).

**Comment by bitinn** [comment]
```lua
local ratio = display.contentWidth / map.data.width
map:scale(ratio, ratio)
```

seem like the best solution at the moment.

**Comment by GymbylCoding** [comment]
This'll probably be part of Dusk 1.0. In the meantime, your approach should be good for now. Keep in mind that Dusk's culling isn't a smooth operation - tiles are drawn in chunks, so if the user can see the side of your tilemap, it could be a little odd-looking. Of course, snapshots could remedy this.

**Comment by bitinn** [comment]
@GymbylCoding another good use-case for viewport would be issues like this:

https://forums.coronalabs.com/topic/61807-spawn-and-move-an-enemy-into-the-map/
