### ISSUE TITLE
Multiple tilesets support

### ISSUE THREAD

**Issue by bitinn** [GymbylCoding/Dusk-Engine#44]
Dusk engine does load json export with multiple tilesets but I think its tile selection are wrong.

What I expect (export image from Tiled):

![shop](https://cloud.githubusercontent.com/assets/1484279/13283957/fcf81bba-db2b-11e5-9289-d2b7371f8a29.png)

What I got (loaded via dusk):

![screen shot 2016-02-24 at 7 23 24 pm](https://cloud.githubusercontent.com/assets/1484279/13283971/1b398a50-db2c-11e5-9923-63d39a58e84c.png)

(ignore the extra player character, it's inserted at runtime)

Sample files with tmx/json export/spritesheets

[sample.zip](https://github.com/GymbylCoding/Dusk-Engine/files/144461/sample.zip)

**Comment by GymbylCoding** [comment]
This looks like its happening because your tileset isn't a multiple of your tile size. I recommend for now that you resize your tileset to be 640x480 or something in that range. I will see about getting Dusk's import matching Tiled for non-integer tile size multiple tilesets.

**Comment by bitinn** [comment]
> tileset isn't a multiple of your tile size

I am not quite sure what you mean by that, tiles in all 3 tilesets are 16x16 with 1px margin.

**Comment by GymbylCoding** [comment]
Sorry, my bad; I was using only the tile size without the spacing. I've fixed this in my personal branch. This'll be done in v1.0.

**Comment by bitinn** [comment]
Run into another render problem, likely related to this issue, this time I tried to merged my tilesets into one set, but also ran into issues...

![shop-alt](https://cloud.githubusercontent.com/assets/1484279/13379506/30d0e32a-de62-11e5-8acb-a635a9101f1e.png)

![screen shot 2016-02-28 at 9 26 31 pm](https://cloud.githubusercontent.com/assets/1484279/13379508/380e0de8-de62-11e5-9f90-377836eafedf.png)

Does this bug affects all non-rectangular spritesheets with spacing? If so this is kinda a blocking issue for me. Do let me know if you got a v1.0-rc or workaround available.

[sample-merged.zip](https://github.com/GymbylCoding/Dusk-Engine/files/149919/sample-merged.zip)

**Comment by bitinn** [comment]
@GymbylCoding I have isolated the problem into this tileset spritesheet, it looks fine in tiled map editor, but when dusk load the export json, tile selections are all wrong.

![roguelike-indoor](https://cloud.githubusercontent.com/assets/1484279/13548355/286b6374-e329-11e5-88af-e32e91abc716.png)

specifically, any tiles on this tileset AND any additional tilesets (inserted after this tileset) will select incorrect tiles.

```json
 "tilesets":[
        {
         "columns":26,
         "firstgid":1,
         "image":"roguelike-indoor.png",
         "imageheight":305,
         "imagewidth":457,
         "margin":0,
         "name":"roguelike-indoor",
         "properties":
            {

            },
         "spacing":1,
         "tilecount":468,
         "tileheight":16,
         "tilewidth":16
        }, 
        {
         "columns":57,
         "firstgid":469,
         "image":"roguelike.png",
         "imageheight":526,
         "imagewidth":968,
         "margin":0,
         "name":"roguelike",
         "properties":
            {

            },
         "spacing":1,
         "tilecount":1767,
         "tileheight":16,
         "tilewidth":16
        }],
```

Is there a way for me to modify said spritesheet to avoid my issue? It's my only solution besides forking dusk v0.2 (given v1.0 is coming and incompatible, I just don't think it's a good idea)

**Comment by GymbylCoding** [comment]
I pushed an update for you. Let me know if it helps.
